### ISSUE TITLE
DB issue on DeleteExpiredScenes

### ISSUE THREAD

**Issue by baldybuilds** [ItsANoBrainer/qb-scenes#3]
Afternoon dude, this script is amazing and thanks for providing this for everyone to use! The recent update is great.
I do just have one DB issue which springs up now and again and I was wondering if anyone has an idea on a fix?

Error:
```
[    script:sn-scenes] SCRIPT ERROR: @sn-scenes/server/server.lua:55: attempt to compare number with table
[    script:sn-scenes] > ref (@sn-scenes/server/server.lua:55)
[    script:sn-scenes] > <unknown> (@ghmattimysql/ghmattimysql-server.js:1)
```

Code Example:
```
function DeleteExpiredScenes()
    exports['ghmattimysql']:execute('DELETE FROM scenes WHERE date_deletion < NOW()', {}, function(result)
LINE 55 -->        if result > 0 then
            print('Deleted '..result..' expired scenes from the database.')
            UpdateAllScenes()
        end
    end)
end
```

**Comment by ItsANoBrainer** [comment]
Thankyou for the support!

What you just posted does not use my code, you or someone changed the database export/function to use ghattimysql. Oxmysql returns a number of tables deleted as the result, what you're using must return a table. Print the table and see what it returns and adjust it accordingly.

**Comment by baldybuilds** [comment]
Yeah, I changed the exports for the DB we use. I just was not sure what this error would indicate. 
I do appreciate you getting back to me though.

**Comment by istoking** [comment]
> Yeah, I changed the exports for the DB we use. I just was not sure what this error would indicate. I do appreciate you getting back to me though.

Did you find a fix for this? I use oxmysql and just checked the result against nil and it works fine: `if result[1] ~= nil then`
