### ISSUE TITLE
No input field for text, no color picker, no duration dropdown

### ISSUE THREAD

**Issue by freezebrr** [ItsANoBrainer/qb-scenes#5]
Over the last day or so, i've noticed the `qb-scenes` interface has changed.

There are no longer the following features:

- input field for text
- color select eyedrop tool, or color input field
- dropdown select for duration

I added some new resources to my main server so I figured they might be conflicting. However, I've seen added the latest release of `qb-scenes` to my test server with no other mods and got the same behaviour.

![qbscene](https://user-images.githubusercontent.com/101987266/163415901-12cb39fc-61a7-48e5-9950-7d624b68a64d.png)

**Comment by ItsANoBrainer** [comment]
Hotfix pushed. Some weirdness with quasar recommending not hardcoding vue version into the HTML, and then vue updating something that broke quasar requiring all 3 to be updated.

**Comment by AKGamingYT0** [comment]
can you please tell how to extent  expiration time or  put text permanet.
